// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-amd64.zst
var embeddedManagedShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "507b67c260eeea02fba87b8f221308fe74111fa56f2b06fdd80107bb1e657720",
		SHA256:       "0492143069e8e65277a8c9185287b0617df74e4eb43e8117ac6e4da471b69d25",
		Zstd:         embeddedManagedShim_linux_amd64,
	})
}
