// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-amd64.zst
var embeddedManagedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "507b67c260eeea02fba87b8f221308fe74111fa56f2b06fdd80107bb1e657720",
		SHA256:       "f13567e5394374d99a421e486a9e27531b2d486663a6fe34eb1ef8d22a435bd8",
		Zstd:         embeddedManagedShim_darwin_amd64,
	})
}
