// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/vscode-shim-windows-amd64.zst
var embeddedManagedShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "507b67c260eeea02fba87b8f221308fe74111fa56f2b06fdd80107bb1e657720",
		SHA256:       "fc93c31aa7c976c84b01c2c51a04ad7063616b2e96960a676d5ccc159a090102",
		Zstd:         embeddedManagedShim_windows_amd64,
	})
}
