// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-arm64.zst
var embeddedManagedShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "507b67c260eeea02fba87b8f221308fe74111fa56f2b06fdd80107bb1e657720",
		SHA256:       "b22482423f37198b87604c5dbd78a0caf3ca70facd935f2c011a1d70e394a3b5",
		Zstd:         embeddedManagedShim_linux_arm64,
	})
}
