// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-arm64.zst
var embeddedManagedShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "507b67c260eeea02fba87b8f221308fe74111fa56f2b06fdd80107bb1e657720",
		SHA256:       "35662777c2e8250183d5e685b0fe53c8ef9d49f19f3c35cb229d93633fbf1c58",
		Zstd:         embeddedManagedShim_darwin_arm64,
	})
}
