// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-amd64.zst
var embeddedUpgradeShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "7610c32b74340a26922e33dbbf04afcef72f884b1f46cf1d65d94a03d1c35512",
		SHA256:       "2e178def63fac62718878f57501119b074d5dcac86d560c93007dad51a9f76f6",
		Zstd:         embeddedUpgradeShim_linux_amd64,
	})
}
