// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-amd64.zst
var embeddedUpgradeShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "7610c32b74340a26922e33dbbf04afcef72f884b1f46cf1d65d94a03d1c35512",
		SHA256:       "13449b2060af64a49be9dfd5ecde37a83342877fb9a4ffe3d7e243f2c9d260d7",
		Zstd:         embeddedUpgradeShim_darwin_amd64,
	})
}
