// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-arm64.zst
var embeddedUpgradeShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "7610c32b74340a26922e33dbbf04afcef72f884b1f46cf1d65d94a03d1c35512",
		SHA256:       "b47a6fa3eb7f5dba1face5de4c9e0d8dc4c73af70b1bc36bdd7cbcca2743ece1",
		Zstd:         embeddedUpgradeShim_linux_arm64,
	})
}
