// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "7610c32b74340a26922e33dbbf04afcef72f884b1f46cf1d65d94a03d1c35512",
		SHA256:       "f6bf735f712c758f77909706fb134373189d1ee4c24b0e66c6cdd1c502d1c7b9",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
