// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64 && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/upgrade-shim-windows-amd64.zst
var embeddedUpgradeShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "7610c32b74340a26922e33dbbf04afcef72f884b1f46cf1d65d94a03d1c35512",
		SHA256:       "1ca5389987c8ff9aee94596a699d7abf6e62554eb6c519da3b8072c50b3045eb",
		Zstd:         embeddedUpgradeShim_windows_amd64,
	})
}
