#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE_DIR="${ROOT_DIR}/internal/managedshim/embed"
ASSET_DIR="${PACKAGE_DIR}/assets"
GOOS_VALUE="${1:-${GOOS:-$(go env GOOS)}}"
GOARCH_VALUE="${2:-${GOARCH:-$(go env GOARCH)}}"
SCRIPT_PATH="${BASH_SOURCE[0]}"

if ! command -v zstd >/dev/null 2>&1; then
  echo "zstd is required to prepare managed shim assets" >&2
  exit 1
fi

checksum_cmd=(sha256sum)
if ! command -v "${checksum_cmd[0]}" >/dev/null 2>&1; then
  checksum_cmd=(shasum -a 256)
fi

checksum_first_field() {
  "${checksum_cmd[@]}" "$1" | awk '{print $1}'
}

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "${tmp_dir}"
  rm -f "${generated_go_tmp}"
}
trap cleanup EXIT

asset_name="vscode-shim-${GOOS_VALUE}-${GOARCH_VALUE}"
binary_path="${tmp_dir}/${asset_name}"
if [[ "${GOOS_VALUE}" == "windows" ]]; then
  binary_path="${binary_path}.exe"
fi

source_digest="$(
  {
    printf 'goversion=%s\n' "$(go env GOVERSION)"
    printf 'script=%s\n' "$(checksum_first_field "${SCRIPT_PATH}")"
    while IFS= read -r -d '' file; do
      printf '%s  %s\n' "$(checksum_first_field "${file}")" "${file#"${ROOT_DIR}/"}"
    done < <(
      find "${ROOT_DIR}/cmd/vscode-shim" "${ROOT_DIR}/internal/app/vscodeshim" "${ROOT_DIR}/internal/managedshim" \
        -type f -name '*.go' \
        ! -path "${ROOT_DIR}/internal/managedshim/embed/*" \
        -print0 |
        sort -z
    )
  } | "${checksum_cmd[@]}" | awk '{print $1}'
)"

mkdir -p "${ASSET_DIR}"
compressed_path="${ASSET_DIR}/${asset_name}.zst"
generated_go="${PACKAGE_DIR}/managed_shim_${GOOS_VALUE}_${GOARCH_VALUE}_embed.go"
generated_go_tmp="${generated_go}.tmp.$$"

if [[ -f "${generated_go}" && -f "${compressed_path}" ]] && grep -Fq "SourceDigest: \"${source_digest}\"" "${generated_go}"; then
  echo "managed shim asset already up to date for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
  exit 0
fi

CGO_ENABLED=0 GOOS="${GOOS_VALUE}" GOARCH="${GOARCH_VALUE}" \
  go build -trimpath -buildvcs=false -ldflags "-s -w" -o "${binary_path}" ./cmd/vscode-shim

binary_sha256="$(checksum_first_field "${binary_path}")"

zstd -19 -q -f -o "${compressed_path}" "${binary_path}"

cat > "${generated_go_tmp}" <<EOF
// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build ${GOOS_VALUE} && ${GOARCH_VALUE} && !codex_remote_upgrade_shim

package embed

import _ "embed"

//go:embed assets/$(basename "${compressed_path}")
var embeddedManagedShim_${GOOS_VALUE}_${GOARCH_VALUE} []byte

func init() {
	register(Asset{
		SourceDigest: "${source_digest}",
		SHA256:       "${binary_sha256}",
		Zstd:         embeddedManagedShim_${GOOS_VALUE}_${GOARCH_VALUE},
	})
}
EOF

gofmt -w "${generated_go_tmp}"
mv "${generated_go_tmp}" "${generated_go}"
echo "prepared managed shim asset for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
